name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark

      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          publish_branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}